spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

  datasource:
    url: jdbc:h2:~/test

  h2:
    console:
      enabled: true
      path: /h2

recycle:
  fixedRate: 30000 # Recycle service runs every 30 seconds.

seatHold:
  expiration: 30000 # SeatHold expires within 30 seconds.
